server {
    listen 80;
    listen [::]:80;
    server_name staging-static.venusface.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name staging-static.venusface.com;

    ssl_certificate /etc/letsencrypt/live/staging-static.venusface.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging-static.venusface.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_ecdh_curve prime256v1:secp384r1;

    client_max_body_size 1024m;
    client_body_timeout 300s;
    access_log /var/log/nginx/flashmuse-test-access.log;
    error_log /var/log/nginx/flashmuse-test-error.log;

    location /home-assets/ {
        alias /var/www/flashmuse-static-test/home-assets/;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=2592000, immutable" always;
        add_header Access-Control-Allow-Origin * always;
    }

    location /_next/static/ {
        alias /var/www/flashmuse-static-test/_next/static/;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=2592000, immutable" always;
        add_header Access-Control-Allow-Origin * always;
    }

    location /generated/ {
        root /var/www/flashmuse-static-test;
        try_files $uri @gen_test_ssl;
        add_header Cache-Control "public, max-age=2592000, immutable" always;
        add_header Access-Control-Allow-Origin * always;
    }

    location @gen_test_ssl {
        proxy_pass http://119.28.116.16:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        add_header Access-Control-Allow-Origin * always;
    }

    location / {
        proxy_pass http://119.28.116.16:5001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_request_buffering off;
    }
}
